on:
  push:
    branches:
    - main
    - release/*
  steps:
- uses: actions/setup-java@v3
  with:
    distribution: 'temurin' # See 'Supported distributions' for available options
    java-version: '17'
- run: java players.java
